"""remove_lesson_plan_outputs_table

Revision ID: 1659473e3b21
Revises: 732257193f2b
Create Date: 2026-01-02 18:55:30.170049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1659473e3b21'
down_revision = '732257193f2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_plan_outputs_id', table_name='lesson_plan_outputs')
    op.drop_index('ix_lesson_plan_outputs_input_id', table_name='lesson_plan_outputs')
    op.drop_table('lesson_plan_outputs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plan_outputs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('input_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['lesson_plan_inputs.id'], name='lesson_plan_outputs_input_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lesson_plan_outputs_pkey')
    )
    op.create_index('ix_lesson_plan_outputs_input_id', 'lesson_plan_outputs', ['input_id'], unique=False)
    op.create_index('ix_lesson_plan_outputs_id', 'lesson_plan_outputs', ['id'], unique=False)
    # ### end Alembic commands ###

