"""add_lesson_plan_session_map_table

Revision ID: 418dbff32a95
Revises: dfb407655df5
Create Date: 2025-12-29 13:49:04.506416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '418dbff32a95'
down_revision = 'dfb407655df5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plan_session_map',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('input_id', sa.BigInteger(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_title', sa.Text(), nullable=False),
    sa.Column('kp_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['lesson_plan_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plan_session_map_id'), 'lesson_plan_session_map', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_session_map_input_id'), 'lesson_plan_session_map', ['input_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_plan_session_map_input_id'), table_name='lesson_plan_session_map')
    op.drop_index(op.f('ix_lesson_plan_session_map_id'), table_name='lesson_plan_session_map')
    op.drop_table('lesson_plan_session_map')
    # ### end Alembic commands ###

