"""remove_redundant_columns_from_session_content

Revision ID: 732257193f2b
Revises: 935697a8d56d
Create Date: 2025-12-30 19:23:59.732159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732257193f2b'
down_revision = '935697a8d56d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_plan_session_content_input_id', table_name='lesson_plan_session_content')
    op.drop_constraint('lesson_plan_session_content_input_id_fkey', 'lesson_plan_session_content', type_='foreignkey')
    op.drop_column('lesson_plan_session_content', 'input_id')
    op.drop_column('lesson_plan_session_content', 'session_title')
    op.drop_column('lesson_plan_session_content', 'session_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plan_session_content', sa.Column('session_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lesson_plan_session_content', sa.Column('session_title', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('lesson_plan_session_content', sa.Column('input_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('lesson_plan_session_content_input_id_fkey', 'lesson_plan_session_content', 'lesson_plan_inputs', ['input_id'], ['id'])
    op.create_index('ix_lesson_plan_session_content_input_id', 'lesson_plan_session_content', ['input_id'], unique=False)
    # ### end Alembic commands ###

