"""add_lesson_plan_session_content_table

Revision ID: 74320982bd68
Revises: 418dbff32a95
Create Date: 2025-12-30 18:48:03.570596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74320982bd68'
down_revision = '418dbff32a95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plan_session_content',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('input_id', sa.BigInteger(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_title', sa.Text(), nullable=False),
    sa.Column('session_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['lesson_plan_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plan_session_content_id'), 'lesson_plan_session_content', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_session_content_input_id'), 'lesson_plan_session_content', ['input_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_plan_session_content_input_id'), table_name='lesson_plan_session_content')
    op.drop_index(op.f('ix_lesson_plan_session_content_id'), table_name='lesson_plan_session_content')
    op.drop_table('lesson_plan_session_content')
    # ### end Alembic commands ###

