"""add_session_id_to_lesson_plan_session_content

Revision ID: 935697a8d56d
Revises: 74320982bd68
Create Date: 2025-12-30 19:00:41.520728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935697a8d56d'
down_revision = '74320982bd68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plan_session_content', sa.Column('session_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_lesson_plan_session_content_session_id'), 'lesson_plan_session_content', ['session_id'], unique=False)
    op.create_foreign_key(None, 'lesson_plan_session_content', 'lesson_plan_session_map', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_plan_session_content', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_plan_session_content_session_id'), table_name='lesson_plan_session_content')
    op.drop_column('lesson_plan_session_content', 'session_id')
    # ### end Alembic commands ###

