"""add_created_by_user_id_to_lesson_plan_inputs

Revision ID: a1b2c3d4e5f6
Revises: 1659473e3b21
Create Date: 2026-02-26 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '1659473e3b21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plan_inputs', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lesson_plan_inputs_created_by_user_id'), 'lesson_plan_inputs', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_plan_inputs_created_by_user_id'), table_name='lesson_plan_inputs')
    op.drop_column('lesson_plan_inputs', 'created_by_user_id')
    # ### end Alembic commands ###
