"""add state_id to boards

Revision ID: cd19a7929622
Revises: 10fff577c0af
Create Date: 2025-12-03 22:01:17.587825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd19a7929622'
down_revision = '10fff577c0af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_boards_state_id'), 'boards', ['state_id'], unique=False)
    op.create_foreign_key(None, 'boards', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_index(op.f('ix_boards_state_id'), table_name='boards')
    op.drop_column('boards', 'state_id')
    # ### end Alembic commands ###

