"""Add is_active to core models

Revision ID: dc819584830d
Revises: cd19a7929622
Create Date: 2025-12-04 14:54:18.091875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc819584830d'
down_revision = 'cd19a7929622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_boards_is_active'), 'boards', ['is_active'], unique=False)
    op.add_column('chapters', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_chapters_is_active'), 'chapters', ['is_active'], unique=False)
    op.add_column('classes', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_classes_is_active'), 'classes', ['is_active'], unique=False)
    op.add_column('states', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_states_is_active'), 'states', ['is_active'], unique=False)
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.add_column('syllabus', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_syllabus_is_active'), 'syllabus', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabus_is_active'), table_name='syllabus')
    op.drop_column('syllabus', 'is_active')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_column('subjects', 'is_active')
    op.drop_index(op.f('ix_states_is_active'), table_name='states')
    op.drop_column('states', 'is_active')
    op.drop_index(op.f('ix_classes_is_active'), table_name='classes')
    op.drop_column('classes', 'is_active')
    op.drop_index(op.f('ix_chapters_is_active'), table_name='chapters')
    op.drop_column('chapters', 'is_active')
    op.drop_index(op.f('ix_boards_is_active'), table_name='boards')
    op.drop_column('boards', 'is_active')
    # ### end Alembic commands ###

