"""Remove sessions, session_key_points, and session_details tables

Revision ID: e8f5a3b2c1d9
Revises: dc819584830d
Create Date: 2025-12-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f5a3b2c1d9'
down_revision = 'dc819584830d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first (in reverse order of creation)
    op.drop_index(op.f('ix_session_key_points_session_id'), table_name='session_key_points')
    op.drop_index(op.f('ix_session_key_points_key_point_id'), table_name='session_key_points')
    op.drop_index(op.f('ix_session_key_points_id'), table_name='session_key_points')
    op.drop_table('session_key_points')
    
    op.drop_index(op.f('ix_session_details_session_id'), table_name='session_details')
    op.drop_index(op.f('ix_session_details_id'), table_name='session_details')
    op.drop_table('session_details')
    
    # Drop sessions table
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_chapter_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate sessions table and dependent tables (in reverse order)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_chapter_id'), 'sessions', ['chapter_id'], unique=False)
    
    op.create_table('session_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('introduction', sa.JSON(), nullable=True),
    sa.Column('main_content', sa.JSON(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('assessment', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('differentiation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_details_id'), 'session_details', ['id'], unique=False)
    op.create_index(op.f('ix_session_details_session_id'), 'session_details', ['session_id'], unique=True)
    
    op.create_table('session_key_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('key_point_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_point_id'], ['key_points.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_key_points_id'), 'session_key_points', ['id'], unique=False)
    op.create_index(op.f('ix_session_key_points_key_point_id'), 'session_key_points', ['key_point_id'], unique=False)
    op.create_index(op.f('ix_session_key_points_session_id'), 'session_key_points', ['session_id'], unique=False)
    # ### end Alembic commands ###
